language: c
before_install:
- sudo apt-get install gcc binutils patch bzip2 flex make gettext pkg-config unzip libz-dev libc6-dev gperf quilt sed ccache
script:
- wget http://home.sch.bme.hu/~matepeter90/upload/OpenWrt-SDK-ar71xx-for-linux-i686-gcc-4.6-linaro_uClibc-0.9.33.2.tar.bz2
- tar -xf OpenWrt-SDK-ar71xx-for-linux-i686-gcc-4.6-linaro_uClibc-0.9.33.2.tar.bz2
- cd OpenWrt-SDK-ar71xx-for-linux-i686-gcc-4.6-linaro_uClibc-0.9.33.2
- ./scripts/feeds update
- ./scripts/feeds install zorp
- sed -i 's/CONFIG_CCACHE=y/#CONFIG_CCACHE is not set/' .config
- export PATH=$PATH:~/OpenWrt-SDK-ar71xx-for-linux-i686-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin
- unset SED
- unset CC
- env
- make package/feeds/packages/python/{compile,install} V=s
branches:
  only:
    - master
