language: c
before_install:
- sudo apt-get install gcc binutils patch bzip2 flex make gettext pkg-config unzip libz-dev libc6-dev gperf quilt sed ccache
script:
- wget http://downloads.openwrt.org/attitude_adjustment/12.09/x86/generic/OpenWrt-SDK-x86-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2.tar.bz2
- tar -xf OpenWrt-SDK-x86-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2.tar.bz2
- cd OpenWrt-SDK-x86-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2
- unset SED
- ./scripts/feeds update
- ./scripts/feeds install python
- sed -i 's/CONFIG_CCACHE=y/#CONFIG_CCACHE is not set/' .config
- make package/feeds/packages/python/{clean,compile} V=s
branches:
  only:
    - master
